// frontend/src/components/ui/Input.vue
<script setup>
import { computed, ref, useSlots } from 'vue';
import { EyeIcon, EyeSlashIcon } from '@heroicons/vue/24/outline';
import { cn } from '../../utils/styles';

const props = defineProps({
  name: {
    type: String,
    default: ''
  },
  modelValue: {
    type: [String, Number],
    default: ''
  },
  type: {
    type: String,
    default: 'text'
  },
  placeholder: {
    type: String,
    default: ''
  },
  disabled: {
    type: Boolean,
    default: false
  },
  readonly: {
    type: Boolean,
    default: false
  },
  error: {
    type: String,
    default: ''
  },
  success: {
    type: String,
    default: ''
  },
  size: {
    type: String,
    default: 'md',
    validator: value => ['sm', 'md', 'lg'].includes(value)
  },
  variant: {
    type: String,
    default: 'default',
    validator: value => ['default', 'filled'].includes(value)
  },
  autocomplete: {
    type: String,
    default: ''
  }
});

const emit = defineEmits(['update:modelValue', 'blur', 'focus', 'keydown', 'keyup']);

const slots = useSlots();
const showPassword = ref(false);

// Computed properties
const inputType = computed(() => {
  if (props.type === 'password') {
    return showPassword.value ? 'text' : 'password';
  }
  return props.type;
});

const hasError = computed(() => !!props.error);
const hasSuccess = computed(() => !!props.success && !hasError.value);
const hasPrefix = computed(() => !!slots.prefix);
const hasSuffix = computed(() => !!slots.suffix || props.type === 'password');

// Input classes
const inputClasses = computed(() => {
  const baseClasses = 'block w-full transition-all duration-300 focus:outline-none font-medium';
  
  const sizeClasses = {
    sm: 'px-3 py-2 text-sm',
    md: 'px-4 py-2 text-sm',
    lg: 'px-4 py-2 text-base'
  };
  
  const variantClasses = {
    default: 'bg-white border-2 shadow-soft hover:shadow-medium',
    filled: 'bg-gray-50 border-2 border-transparent shadow-soft hover:shadow-medium'
  };
  
  const stateClasses = hasError.value
    ? 'border-error-400 focus:border-error-500 focus:ring-4 focus:ring-error-100 focus:shadow-colored-energy'
    : hasSuccess.value
    ? 'border-success-400 focus:border-success-500 focus:ring-4 focus:ring-success-100 focus:shadow-colored-primary'
    : 'border-gray-300 focus:border-primary-500 focus:ring-4 focus:ring-primary-100 focus:shadow-colored-primary';
  
  const roundingClasses = 'rounded-2xl';

  return cn(
    baseClasses,
    sizeClasses[props.size],
    variantClasses[props.variant],
    stateClasses,
    roundingClasses,
    'focus:ring-offset-0',
    {
      'opacity-50 cursor-not-allowed': props.disabled,
      'pl-12': hasPrefix.value,
      'pr-12': hasSuffix.value
    }
  );
});

const containerClasses = computed(() => {
  return cn(
    'relative flex items-center group',
    {
      'opacity-50': props.disabled
    }
  );
});

// Event handlers
const handleInput = (event) => {
  emit('update:modelValue', event.target.value);
};

const handleBlur = (event) => {
  emit('blur', event);
};

const handleFocus = (event) => {
  emit('focus', event);
};

const handleKeydown = (event) => {
  emit('keydown', event);
};

const handleKeyup = (event) => {
  emit('keyup', event);
};

const togglePasswordVisibility = () => {
  showPassword.value = !showPassword.value;
};
</script>

<template>
  <div class="w-full">
    <div :class="containerClasses">
      <!-- Prefix slot -->
      <div
        v-if="hasPrefix"
        class="absolute left-4 z-10 flex items-center pointer-events-none"
        :class="{
          'text-error-500': hasError,
          'text-success-500': hasSuccess,
          'text-gray-400': !hasError && !hasSuccess
        }"
      >
        <slot name="prefix" />
      </div>

      <!-- Input element -->
      <input
        :name="name"
        :type="inputType"
        :value="modelValue"
        :placeholder="placeholder"
        :disabled="disabled"
        :readonly="readonly"
        :class="inputClasses"
        :autocomplete="autocomplete"
        @input="handleInput"
        @blur="handleBlur"
        @focus="handleFocus"
        @keydown="handleKeydown"
        @keyup="handleKeyup"
      />

      <!-- Suffix slot or password toggle -->
      <div
        v-if="hasSuffix"
        class="absolute right-4 z-10 flex items-center"
      >
        <button
          v-if="type === 'password'"
          type="button"
          class="text-gray-400 hover:text-gray-600 focus:outline-none"
          @click="togglePasswordVisibility"
        >
          <EyeIcon v-if="!showPassword" class="w-5 h-5" />
          <EyeSlashIcon v-else class="w-5 h-5" />
        </button>
        <div
          v-else
          class="pointer-events-none"
          :class="{
            'text-error-500': hasError,
            'text-success-500': hasSuccess,
            'text-gray-400': !hasError && !hasSuccess
          }"
        >
          <slot name="suffix" />
        </div>
      </div>
    </div>

    <!-- Error message -->
    <p v-if="hasError" class="form-error">
      {{ error }}
    </p>

    <!-- Success message -->
    <p v-if="hasSuccess" class="form-success">
      {{ success }}
    </p>
  </div>
</template>

// gestion-emballages-v2/frontend/src/app/shared/components/ui/input.component.ts
import { Component, Input, Output, EventEmitter, forwardRef, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

type InputSize = 'sm' | 'md' | 'lg';
type InputType = 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' | 'search';

@Component({
  selector: 'ui-input',
  standalone: true,
  imports: [CommonModule],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true
    }
  ],
  template: `
    <div class="space-y-1">
      <!-- Label -->
      <label 
        *ngIf="label"
        [for]="inputId"
        class="block text-sm font-medium text-gray-700">
        {{ label }}
        <span *ngIf="required" class="text-error-500">*</span>
      </label>

      <!-- Input Container -->
      <div class="relative">
        <!-- Left Icon -->
        <div 
          *ngIf="hasLeftIcon"
          class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="leftIcon" />
          </svg>
        </div>

        <!-- Input Element -->
        <input
          [id]="inputId"
          [type]="type"
          [value]="value"
          [placeholder]="placeholder"
          [disabled]="disabled"
          [readonly]="readonly"
          [required]="required"
          [autocomplete]="autocomplete"
          [class]="inputClasses()"
          (input)="onInput($event)"
          (blur)="onBlur()"
          (focus)="onFocus()"
        />

        <!-- Right Icon -->
        <div 
          *ngIf="rightIcon"
          class="absolute inset-y-0 right-0 pr-3 flex items-center">
          <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="rightIcon" />
          </svg>
        </div>

        <!-- Clear Button -->
        <button
          *ngIf="clearable && value && !disabled"
          type="button"
          class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
          (click)="clearValue()">
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Help Text -->
      <p 
        *ngIf="helpText && !error"
        class="text-sm text-gray-500">
        {{ helpText }}
      </p>

      <!-- Error Message -->
      <p 
        *ngIf="error"
        class="text-sm text-error-600">
        {{ error }}
      </p>
    </div>
  `
})
export class InputComponent implements ControlValueAccessor {
  @Input() label = '';
  @Input() type: InputType = 'text';
  @Input() size: InputSize = 'md';
  @Input() placeholder = '';
  @Input() helpText = '';
  @Input() error = '';
  @Input() disabled = false;
  @Input() readonly = false;
  @Input() required = false;
  @Input() clearable = false;
  @Input() autocomplete = '';
  @Input() inputId = `input-${Math.random().toString(36).substr(2, 9)}`;
  @Input() leftIcon = '';  // SVG path string for left icon
  @Input() rightIcon = ''; // SVG path string for right icon

  @Output() inputChange = new EventEmitter<string>();
  @Output() inputFocus = new EventEmitter<void>();
  @Output() inputBlur = new EventEmitter<void>();

  value = '';

  get hasLeftIcon() {
    return !!this.leftIcon;
  }

  get hasRightIcon() {
    return !!this.rightIcon || this.clearable;
  }

  private onChange = (value: string) => {};
  private onTouched = () => {};


  inputClasses = computed(() => {
    const baseClasses = [
      'block',
      'w-full',
      'border',
      'rounded-md',
      'shadow-sm',
      'transition-colors',
      'duration-200',
      'focus:outline-none',
      'focus:ring-2',
      'focus:ring-primary-500',
      'focus:border-primary-500',
      'disabled:bg-gray-50',
      'disabled:text-gray-500',
      'disabled:cursor-not-allowed',
      'placeholder-gray-400'
    ];

    // Size classes
    const sizeClasses = {
      sm: ['px-3', 'py-1.5', 'text-sm'],
      md: ['px-3', 'py-2', 'text-sm'],
      lg: ['px-4', 'py-3', 'text-base']
    };

    // State classes
    const stateClasses = this.error 
      ? ['border-error-300', 'text-error-900', 'placeholder-error-300', 'focus:ring-error-500', 'focus:border-error-500']
      : ['border-gray-300'];

    // Padding adjustments for icons
    const paddingClasses = [];
    if (this.hasLeftIcon) {
      paddingClasses.push('pl-10');
    }
    if (this.rightIcon || this.clearable) {
      paddingClasses.push('pr-10');
    }

    return [
      ...baseClasses,
      ...sizeClasses[this.size],
      ...stateClasses,
      ...paddingClasses
    ].join(' ');
  });

  onInput(event: Event) {
    const target = event.target as HTMLInputElement;
    this.value = target.value;
    this.onChange(this.value);
    this.inputChange.emit(this.value);
  }

  onFocus() {
    this.inputFocus.emit();
  }

  onBlur() {
    this.onTouched();
    this.inputBlur.emit();
  }

  clearValue() {
    this.value = '';
    this.onChange(this.value);
    this.inputChange.emit(this.value);
  }

  // ControlValueAccessor implementation
  writeValue(value: string): void {
    this.value = value || '';
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}
