// gestion-emballages-v2/frontend/src/app/features/fournisseurs/fournisseur-list/fournisseur-list.component.ts
import { Component, OnInit, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';

import { Fournisseur, FournisseurFilters } from '../../../core/models/fournisseur.model';
import { FournisseurService } from '../../../core/services/fournisseur.service';
import { AuthService } from '../../../core/services/auth.service';
import { LoadingService } from '../../../core/services/loading.service';
import { ToastService } from '../../../core/services/toast.service';
import { UserRole } from '../../../core/models/user.model';

@Component({
  selector: 'app-fournisseur-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-gray-900">Gestion des Fournisseurs</h1>
        <button 
          *ngIf="canCreateFournisseur()"
          class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
          [routerLink]="['/fournisseurs/nouveau']">
          Nouveau Fournisseur
        </button>
      </div>

      <!-- Search and Filters -->
      <div class="space-y-4">
        <div class="flex items-center space-x-4">
          <button 
            (click)="showFilters.set(!showFilters())"
            class="flex items-center space-x-2 px-3 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
            <span>Filtres</span>
            <span *ngIf="activeFiltersCount() > 0" 
                  class="bg-blue-600 text-white text-xs px-2 py-1 rounded-full">
              {{ activeFiltersCount() }}
            </span>
          </button>
          
          <div class="flex-1 relative">
            <input
              type="text"
              [(ngModel)]="searchQuery"
              (input)="onSearchChange()"
              placeholder="Rechercher par nom, SIRET, ville..."
              class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
            </div>
          </div>
        </div>

        <!-- Filter Panel -->
        <div *ngIf="showFilters()" class="p-4 bg-gray-50 rounded-lg">
          <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Statut</label>
              <select 
                [(ngModel)]="filters.status"
                (change)="applyFilters()"
                class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">
                <option value="">Tout</option>
                <option value="active">Actif</option>
                <option value="inactive">Inactif</option>
              </select>
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Spécialité</label>
              <select 
                [(ngModel)]="filters.specialite"
                (change)="applyFilters()"
                class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">
                <option value="">Toutes</option>
                <option value="Emballage">Emballage</option>
                <option value="Carton">Carton</option>
                <option value="Plastique">Plastique</option>
                <option value="Bois">Bois</option>
              </select>
            </div>
          </div>
          
          <div class="flex justify-end">
            <button 
              (click)="clearFilters()"
              class="px-4 py-2 text-sm text-gray-600 hover:text-gray-800">
              Réinitialiser les filtres
            </button>
          </div>
        </div>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading()" class="text-center py-8">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
        <p class="mt-2 text-gray-600">Chargement...</p>
      </div>

      <!-- Pagination Controls -->
      <div *ngIf="!loading() && totalPages() > 1" class="flex items-center justify-between border-b border-gray-200 px-6 py-2">
        <div class="text-xs text-gray-700">
          Affichage de {{ (currentPage() - 1) * itemsPerPage() + 1 }} à {{ Math.min(currentPage() * itemsPerPage(), totalItems()) }} sur {{ totalItems() }} résultats
        </div>
        <div class="flex items-center space-x-4">
          <div class="flex items-center space-x-2">
            <span class="text-xs text-gray-700">Afficher:</span>
            <select [value]="itemsPerPage()" (change)="changeItemsPerPage($event)" 
                    class="border border-gray-300 rounded px-2 py-0.5 text-xs bg-white w-14 focus:ring-1 focus:ring-primary-500 focus:border-primary-500">
              <option value="10">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
            </select>
            <span class="text-xs text-gray-700">par page</span>
          </div>
          <div class="flex space-x-1">
            <button [disabled]="currentPage() === 1" (click)="goToPage(currentPage() - 1)"
                    class="px-2 py-0.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed">
              Précédent
            </button>
            <button *ngFor="let page of getVisiblePages()" (click)="goToPage(page)"
                    [class.bg-primary-100]="page === currentPage()"
                    [class.text-primary-700]="page === currentPage()"
                    class="px-2 py-0.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50">
              {{ page }}
            </button>
            <button [disabled]="currentPage() === totalPages()" (click)="goToPage(currentPage() + 1)"
                    class="px-2 py-0.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed">
              Suivant
            </button>
          </div>
        </div>
      </div>

      <!-- Desktop Table -->
      <div *ngIf="!loading()" class="hidden md:block bg-white shadow rounded-lg overflow-hidden">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer"
                  (click)="toggleSort('nom')">
                Nom
                <svg *ngIf="filters.sortBy === 'nom'" class="inline w-4 h-4 ml-1" fill="currentColor" viewBox="0 0 20 20">
                  <path *ngIf="filters.sortOrder === 'ASC'" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"/>
                  <path *ngIf="filters.sortOrder === 'DESC'" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"/>
                </svg>
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">SIRET</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Contact</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Spécialités</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Statut</th>
              <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr *ngFor="let fournisseur of fournisseurs()" class="hover:bg-gray-50">
              <td class="px-6 py-4 whitespace-nowrap">
                <div>
                  <div class="text-sm font-medium text-gray-900">{{ fournisseur.nom }}</div>
                  <div class="text-sm text-gray-500">{{ fournisseur.ville }}</div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ fournisseur.siret }}</td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ fournisseur.contact }}</div>
                <div class="text-sm text-gray-500">{{ fournisseur.email }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex flex-wrap gap-1">
                  <span *ngFor="let specialite of fournisseur.specialites" 
                        class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                    {{ specialite }}
                  </span>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span [class]="getStatusBadgeClass(fournisseur.isActive)">
                  {{ fournisseur.isActive ? 'Actif' : 'Inactif' }}
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <div class="flex items-center justify-end space-x-2">
                  <button 
                    [routerLink]="['/fournisseurs', fournisseur.id]"
                    class="text-blue-600 hover:text-blue-900">
                    Voir
                  </button>
                  <button 
                    *ngIf="canEditFournisseur()"
                    [routerLink]="['/fournisseurs', fournisseur.id, 'modifier']"
                    class="text-green-600 hover:text-green-900">
                    Modifier
                  </button>
                  <button 
                    *ngIf="canToggleStatus()"
                    (click)="toggleStatus(fournisseur)"
                    [class]="fournisseur.isActive ? 'text-red-600 hover:text-red-900' : 'text-green-600 hover:text-green-900'">
                    {{ fournisseur.isActive ? 'Désactiver' : 'Activer' }}
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Mobile Cards -->
      <div *ngIf="!loading()" class="md:hidden space-y-4">
        <div *ngFor="let fournisseur of fournisseurs()" 
             class="bg-white p-4 rounded-lg shadow border border-gray-200">
          <div class="flex items-start justify-between mb-3">
            <div>
              <h3 class="font-medium text-gray-900">{{ fournisseur.nom }}</h3>
              <p class="text-sm text-gray-500">{{ fournisseur.ville }}</p>
            </div>
            <span [class]="getStatusBadgeClass(fournisseur.isActive)">
              {{ fournisseur.isActive ? 'Actif' : 'Inactif' }}
            </span>
          </div>
          
          <div class="space-y-2 text-sm">
            <div><span class="font-medium">SIRET:</span> {{ fournisseur.siret }}</div>
            <div *ngIf="fournisseur.contact"><span class="font-medium">Contact:</span> {{ fournisseur.contact }}</div>
            <div *ngIf="fournisseur.email"><span class="font-medium">Email:</span> {{ fournisseur.email }}</div>
            <div *ngIf="fournisseur.specialites.length > 0">
              <span class="font-medium">Spécialités:</span>
              <div class="flex flex-wrap gap-1 mt-1">
                <span *ngFor="let specialite of fournisseur.specialites" 
                      class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                  {{ specialite }}
                </span>
              </div>
            </div>
          </div>
          
          <div class="flex items-center justify-end space-x-3 mt-4 pt-3 border-t border-gray-200">
            <button 
              [routerLink]="['/fournisseurs', fournisseur.id]"
              class="text-blue-600 hover:text-blue-900 text-sm">
              Voir
            </button>
            <button 
              *ngIf="canEditFournisseur()"
              [routerLink]="['/fournisseurs', fournisseur.id, 'modifier']"
              class="text-green-600 hover:text-green-900 text-sm">
              Modifier
            </button>
            <button 
              *ngIf="canToggleStatus()"
              (click)="toggleStatus(fournisseur)"
              [class]="fournisseur.isActive ? 'text-red-600 hover:text-red-900 text-sm' : 'text-green-600 hover:text-green-900 text-sm'">
              {{ fournisseur.isActive ? 'Désactiver' : 'Activer' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Empty State -->
      <div *ngIf="!loading() && fournisseurs().length === 0" class="text-center py-12">
        <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-4m-4 0H3m2 0h3M9 7h6m-6 4h6m-6 4h6"/>
        </svg>
        <p class="mt-4 text-gray-500">Aucun fournisseur trouvé</p>
        <button 
          *ngIf="canCreateFournisseur()"
          [routerLink]="['/fournisseurs/nouveau']"
          class="mt-4 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
          Créer le premier fournisseur
        </button>
      </div>
    </div>
  `
})
export class FournisseurListComponent implements OnInit {
  // Signals
  fournisseurs = signal<Fournisseur[]>([]);
  loading = signal(false);
  showFilters = signal(false);
  currentPage = signal(1);
  totalPages = signal(0);
  totalItems = signal(0);
  itemsPerPage = signal(10);

  // Filter state
  searchQuery = '';
  filters: FournisseurFilters = {
    page: 1,
    limit: 10,
    search: '',
    sortBy: 'nom',
    sortOrder: 'ASC',
    status: '',
    specialite: ''
  };

  // Computed
  activeFiltersCount = computed(() => {
    let count = 0;
    if (this.filters.status) count++;
    if (this.filters.specialite) count++;
    return count;
  });

  private searchTimeout: any;

  // Expose Math to template
  Math = Math;

  constructor(
    private fournisseurService: FournisseurService,
    private authService: AuthService,
    private loadingService: LoadingService,
    private toastService: ToastService
  ) {}

  ngOnInit() {
    this.loadFournisseurs();
  }

  async loadFournisseurs() {
    this.loading.set(true);
    try {
      const response = await this.fournisseurService.getFournisseurs(this.filters);
      this.fournisseurs.set(response.data);
      this.totalPages.set(response.totalPages);
      this.totalItems.set(response.total);
      this.currentPage.set(response.page);
    } catch (error) {
      this.toastService.error('Erreur lors du chargement des fournisseurs');
    } finally {
      this.loading.set(false);
    }
  }

  onSearchChange() {
    if (this.searchTimeout) {
      clearTimeout(this.searchTimeout);
    }
    this.searchTimeout = setTimeout(() => {
      this.filters.search = this.searchQuery;
      this.filters.page = 1;
      this.loadFournisseurs();
    }, 300);
  }

  applyFilters() {
    this.filters.page = 1;
    this.loadFournisseurs();
  }

  clearFilters() {
    this.searchQuery = '';
    this.filters = {
      page: 1,
      limit: 10,
      search: '',
      sortBy: 'nom',
      sortOrder: 'ASC',
      status: '',
      specialite: ''
    };
    this.loadFournisseurs();
  }

  toggleSort(field: string) {
    if (this.filters.sortBy === field) {
      this.filters.sortOrder = this.filters.sortOrder === 'ASC' ? 'DESC' : 'ASC';
    } else {
      this.filters.sortBy = field;
      this.filters.sortOrder = 'ASC';
    }
    this.loadFournisseurs();
  }

  goToPage(page: number) {
    if (page >= 1 && page <= this.totalPages()) {
      this.filters.page = page;
      this.loadFournisseurs();
    }
  }

  changeItemsPerPage(event: Event) {
    const target = event.target as HTMLSelectElement;
    this.itemsPerPage.set(parseInt(target.value));
    this.filters.limit = parseInt(target.value);
    this.filters.page = 1;
    this.loadFournisseurs();
  }

  getVisiblePages(): number[] {
    const total = this.totalPages();
    const current = this.currentPage();
    const pages: number[] = [];

    if (total <= 7) {
      for (let i = 1; i <= total; i++) {
        pages.push(i);
      }
    } else {
      if (current <= 4) {
        for (let i = 1; i <= 5; i++) {
          pages.push(i);
        }
        pages.push(-1, total);
      } else if (current >= total - 3) {
        pages.push(1, -1);
        for (let i = total - 4; i <= total; i++) {
          pages.push(i);
        }
      } else {
        pages.push(1, -1);
        for (let i = current - 1; i <= current + 1; i++) {
          pages.push(i);
        }
        pages.push(-1, total);
      }
    }

    return pages;
  }

  async toggleStatus(fournisseur: Fournisseur) {
    try {
      if (fournisseur.isActive) {
        await this.fournisseurService.deactivateFournisseur(fournisseur.id);
        this.toastService.success('Fournisseur désactivé avec succès');
      } else {
        await this.fournisseurService.reactivateFournisseur(fournisseur.id);
        this.toastService.success('Fournisseur réactivé avec succès');
      }
      this.loadFournisseurs();
    } catch (error) {
      this.toastService.error('Erreur lors de la modification du statut');
    }
  }

  getStatusBadgeClass(isActive: boolean): string {
    return isActive 
      ? 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800'
      : 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800';
  }

  // Permission methods
  canCreateFournisseur(): boolean {
    const user = this.authService.currentUser();
    return user?.role === UserRole.MANAGER || user?.role === UserRole.HANDLER;
  }

  canEditFournisseur(): boolean {
    const user = this.authService.currentUser();
    return user?.role === UserRole.MANAGER || user?.role === UserRole.HANDLER;
  }

  canToggleStatus(): boolean {
    const user = this.authService.currentUser();
    return user?.role === UserRole.MANAGER || user?.role === UserRole.HANDLER;
  }
}

// frontend/src/components/FournisseurList.vue
<script setup>
import { useFournisseurList } from '../composables/useFournisseurList';
import { PencilSquareIcon, PlusIcon, ChevronRightIcon, PlayIcon, PauseIcon, ChevronDownIcon, ChevronUpIcon, MagnifyingGlassIcon, FunnelIcon, ChevronDoubleDownIcon, ChevronDoubleUpIcon } from '@heroicons/vue/24/outline';
import SlidePanel from './ui/SlidePanel.vue';
import SiteCreateForm from './fournisseurs/SiteCreateForm.vue';
import FournisseurEditForm from './fournisseurs/FournisseurEditForm.vue';
import SiteEditForm from './fournisseurs/SiteEditForm.vue';
import Button from './ui/Button.vue';
import Select from './ui/Select.vue';

// Use the main fournisseur list composable
const {
  // Data
  fournisseurs,
  transformedTableData,
  isLoading,
  
  // Filters
  searchQuery,
  statusFilter,
  showFilters,
  activeFiltersCount,
  statusOptions,
  
  // Pagination
  currentPage,
  totalPages,
  totalItems,
  itemsPerPage,
  hasNextPage,
  hasPrevPage,
  paginationPages,
  
  // Tree state
  isExpanded,
  toggleExpanded,
  computedIsTreeExpanded,
  toggleTreeState,
  handleExpandAll,
  handleCollapseAll,
  
  // UI state
  isSiteCreatePanelOpen,
  isEditPanelOpen,
  isSiteEditPanelOpen,
  selectedFournisseurForSite,
  selectedFournisseurForEdit,
  selectedSiteForEdit,
  selectedFournisseurIdForSiteEdit,
  
  // Methods
  handlePageChange,
  handlePageSizeChangeWithRefresh,
  handleClearFilters,
  formatAddress,
  editFournisseur,
  openSiteCreatePanel,
  editSite,
  handleSiteCreatedWithRefresh,
  handleFournisseurUpdatedWithRefresh,
  handleSiteUpdatedWithRefresh,
  handleSoftDeleteFournisseur,
  handleReactivateFournisseur,
  handleDeactivateSite,
  handleReactivateSite,
  closeAllPanels,
  
  // Expose for parent component
  fetchFournisseurs,
  goToPrevPage,
  goToNextPage
} = useFournisseurList();

// Expose fetchFournisseurs function for parent component
defineExpose({ fetchFournisseurs });
</script>

<template>
  <div class="space-y-6">
    <!-- Search and Filters -->
    <div class="space-y-4">
      <!-- Search Bar and Filter Toggle -->
      <div class="flex items-center space-x-4">
        <!-- Tree toggle button -->
        <button
          @click="toggleTreeState"
          class="flex-shrink-0 inline-flex items-center justify-center p-2 border border-gray-300 shadow-sm rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
          :title="computedIsTreeExpanded ? 'Tout replier' : 'Tout déplier'"
        >
          <ChevronDoubleUpIcon v-if="computedIsTreeExpanded" class="h-4 w-4" />
          <ChevronDoubleDownIcon v-else class="h-4 w-4" />
        </button>
        
        <button
          @click="showFilters = !showFilters"
          class="flex-shrink-0 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
        >
          <FunnelIcon class="h-4 w-4 mr-2" />
          Filtres
          <span v-if="activeFiltersCount > 0" class="ml-1 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-primary-600 bg-primary-100 rounded-full">
            {{ activeFiltersCount }}
          </span>
          <ChevronDownIcon 
            class="ml-2 h-4 w-4 transition-transform duration-200" 
            :class="{ 'rotate-180': showFilters }"
          />
        </button>
        
        <div class="flex-1 relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <MagnifyingGlassIcon class="h-5 w-5 text-gray-400" />
          </div>
          <input
            v-model="searchQuery"
            type="text"
            class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
            placeholder="Rechercher par nom, spécialisation, sites ou contacts..."
          />
        </div>
      </div>

      <!-- Filters -->
      <div v-if="showFilters" class="p-4 bg-gray-50 rounded-lg">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Statut</label>
            <Select
              v-model="statusFilter"
              :options="statusOptions"
              placeholder="Sélectionner un statut"
            />
          </div>
          
          <!-- Three empty columns for future filters -->
          <div></div>
          <div></div>
          <div></div>
        </div>
        
        <div class="flex justify-end">
          <Button variant="secondary" size="sm" @click="handleClearFilters">
            Réinitialiser les filtres
          </Button>
        </div>
      </div>
    </div>
    
    <!-- Mobile tree view controls -->
    <div class="block md:hidden mb-4">
      <div class="flex items-center justify-start">
        <button 
          @click="toggleTreeState"
          class="inline-flex items-center px-3 py-2 text-sm font-medium text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors"
          :title="computedIsTreeExpanded ? 'Tout replier' : 'Tout déplier'"
        >
          <ChevronDoubleUpIcon v-if="isTreeExpanded" class="h-4 w-4 mr-2" />
          <ChevronDoubleDownIcon v-else class="h-4 w-4 mr-2" />
          {{ computedIsTreeExpanded ? 'Replier tout' : 'Déplier tout' }}
        </button>
      </div>
    </div>
    
    <!-- Mobile card view -->
    <div class="block md:hidden">
      <div class="space-y-3">
        <div
          v-for="fournisseur in transformedTableData"
          :key="fournisseur.key"
          class="p-4 rounded-lg border bg-white border-gray-200"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1 min-w-0">
              <div class="flex items-center justify-between mb-2">
                <div class="flex items-center">
                  <h3 class="text-sm font-semibold truncate text-gray-900">{{ fournisseur.nom }}</h3>
                </div>
                <button
                  v-if="fournisseur.children.length > 0"
                  @click="toggleExpanded(fournisseur.key)"
                  class="flex items-center p-1 hover:bg-gray-100 rounded transition-colors"
                  :title="isExpanded(fournisseur.key) ? 'Réduire' : 'Étendre'"
                >
                  <ChevronRightIcon 
                    :class="['h-4 w-4 text-gray-500 transition-transform duration-200', isExpanded(fournisseur.key) ? 'transform rotate-90' : '']"
                  />
                </button>
              </div>
              <p class="text-sm text-gray-500 truncate">{{ fournisseur.siret }}</p>
              <p class="text-xs text-gray-400 mt-1">{{ formatAddress(fournisseur.adresse) }}</p>
              <div class="mt-2">
                <span v-if="fournisseur.isActive" class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                  Actif
                </span>
                <span v-else class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/20">
                  Inactif
                </span>
              </div>
            </div>
          </div>
          <div class="mt-3 flex justify-end gap-x-2">
            <button 
              @click="editFournisseur(fournisseur)" 
              class="p-2 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
              title="Modifier"
            >
              <PencilSquareIcon class="h-5 w-5" />
            </button>
            <button 
              v-if="fournisseur.isActive"
              @click="handleSoftDeleteFournisseur(fournisseur._id)" 
              class="p-2 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
              title="Désactiver"
            >
              <PauseIcon class="h-5 w-5" />
            </button>
            <button 
              v-else
              @click="handleReactivateFournisseur(fournisseur._id)" 
              class="p-2 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
              title="Réactiver"
            >
              <PlayIcon class="h-5 w-5" />
            </button>
          </div>
          
          <!-- Sites (children) for mobile -->
          <div v-if="isExpanded(fournisseur.key) && fournisseur.children.length > 0" class="mt-4 pl-4 border-l-2 border-gray-200">
            <div v-for="site in fournisseur.children" :key="site._id" class="py-2 border-b border-gray-100 last:border-b-0">
              <div class="flex items-center justify-between">
                <div class="flex-1">
                  <h4 class="text-sm font-medium text-gray-700">{{ site.nomSite }}</h4>
                  <p class="text-xs text-gray-500">{{ formatAddress(site.adresse) }}</p>
                  <div v-if="site.contact" class="text-xs text-gray-400 mt-1">
                    {{ site.contact.nom }} - 
                    <a v-if="site.contact.email" :href="`mailto:${site.contact.email}`" class="text-blue-600 hover:text-blue-800 underline">{{ site.contact.email }}</a>
                    <span v-if="site.contact.email && site.contact.telephone"> / </span>
                    <span v-if="site.contact.telephone">{{ site.contact.telephone }}</span>
                  </div>
                  <span v-if="site.estPrincipal" class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20 mt-1">
                    Principal
                  </span>
                </div>
                <div class="flex gap-x-1">
                  <button 
                    @click="editSite(site, fournisseur._id)"
                    class="p-1 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                    title="Modifier"
                  >
                    <PencilSquareIcon class="h-4 w-4" />
                  </button>
                  <button 
                    v-if="site.isActive !== false"
                    @click="handleDeactivateSite(fournisseur._id, site._id)"
                    class="p-1 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                    title="Désactiver"
                  >
                    <PauseIcon class="h-4 w-4" />
                  </button>
                  <button 
                    v-else
                    @click="handleReactivateSite(fournisseur._id, site._id)"
                    class="p-1 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                    title="Réactiver"
                  >
                    <PlayIcon class="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Loading state for mobile -->
      <div v-if="isLoading" class="flex items-center justify-center py-8">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
      </div>
    </div>

    <!-- Desktop table view -->
    <div class="hidden md:block flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <div class="relative">
            <table class="min-w-full table-fixed divide-y divide-gray-300">
              <thead>
                <tr>
                  <th scope="col" class="min-w-[12rem] py-3.5 pr-3 text-left text-sm font-semibold text-gray-900">Nom Fournisseur / Site</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">SIRET / Principal</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Adresse</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Contact</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Statut</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                    <span class="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white">
                <template v-for="parentItem in transformedTableData" :key="parentItem.key">
                  <!-- Parent row (Fournisseur) -->
                  <tr class="border-b border-gray-200 bg-gray-50">
                    <td class="whitespace-nowrap py-4 pr-3 text-sm font-medium text-gray-900">
                      <div class="flex items-center">
                        <button
                          v-if="parentItem.children.length > 0"
                          @click="toggleExpanded(parentItem.key)"
                          class="flex items-center p-1 hover:bg-gray-100 rounded transition-colors mr-2"
                          :title="isExpanded(parentItem.key) ? 'Réduire' : 'Étendre'"
                        >
                          <ChevronRightIcon 
                            :class="['h-4 w-4 text-gray-500 transition-transform duration-200', isExpanded(parentItem.key) ? 'transform rotate-90' : '']"
                          />
                        </button>
                        <span class="font-semibold text-gray-900">{{ parentItem.nom }}</span>
                      </div>
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-700 font-medium">
                      {{ parentItem.siret }}
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                      {{ formatAddress(parentItem.adresse) }}
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                      <!-- Contact info for parent if needed -->
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm">
                      <span v-if="parentItem.isActive" class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                        Actif
                      </span>
                      <span v-else class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/20">
                        Inactif
                      </span>
                    </td>
                    <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                      <div class="flex items-center justify-end gap-x-2">
                        <button 
                          @click="openSiteCreatePanel(parentItem)"
                          class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                          title="Ajouter un site"
                        >
                          <PlusIcon class="h-5 w-5" />
                        </button>
                        <button 
                          @click="editFournisseur(parentItem)" 
                          class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                          title="Modifier"
                        >
                          <PencilSquareIcon class="h-5 w-5" />
                        </button>
                        <button 
                          v-if="parentItem.isActive"
                          @click="handleSoftDeleteFournisseur(parentItem._id)" 
                          class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                          title="Désactiver"
                        >
                          <PauseIcon class="h-5 w-5" />
                        </button>
                        <button 
                          v-else
                          @click="handleReactivateFournisseur(parentItem._id)" 
                          class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                          title="Réactiver"
                        >
                          <PlayIcon class="h-5 w-5" />
                        </button>
                      </div>
                    </td>
                  </tr>

                  <!-- Child rows (Sites) -->
                  <template v-if="isExpanded(parentItem.key)">
                    <tr v-for="childItem in parentItem.children" :key="childItem._id" class="bg-white hover:bg-gray-25 border-b border-gray-100">
                      <td class="whitespace-nowrap py-3 pr-3 text-sm text-gray-700">
                        <div class="flex items-center pl-8">
                          <div class="w-4 h-4 mr-2 flex items-center justify-center">
                            <div class="w-2 h-2 bg-gray-300 rounded-full"></div>
                          </div>
                          {{ childItem.nomSite }}
                        </div>
                      </td>
                      <td class="whitespace-nowrap px-3 py-3 text-sm text-gray-600">
                        <span v-if="childItem.estPrincipal" class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                          Principal
                        </span>
                      </td>
                      <td class="whitespace-nowrap px-3 py-3 text-sm text-gray-500">
                        {{ formatAddress(childItem.adresse) }}
                      </td>
                      <td class="whitespace-nowrap px-3 py-3 text-sm text-gray-500">
                        <div v-if="childItem.contact">
                          <div>{{ childItem.contact.nom }}</div>
                          <div class="text-gray-400">
                            <a v-if="childItem.contact.email" :href="`mailto:${childItem.contact.email}`" class="text-blue-600 hover:text-blue-800 underline">{{ childItem.contact.email }}</a>
                            <span v-if="childItem.contact.email && childItem.contact.telephone"> / </span>
                            <span v-if="childItem.contact.telephone">{{ childItem.contact.telephone }}</span>
                          </div>
                        </div>
                      </td>
                      <td class="whitespace-nowrap px-3 py-3 text-sm">
                        <!-- Status column empty for sites -->
                      </td>
                      <td class="whitespace-nowrap py-3 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                        <div class="flex items-center justify-end gap-x-2">
                          <button 
                            @click="editSite(childItem, parentItem._id)"
                            class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                            title="Modifier"
                          >
                            <PencilSquareIcon class="h-5 w-5" />
                          </button>
                          <button 
                            v-if="childItem.isActive !== false"
                            @click="handleDeactivateSite(parentItem._id, childItem._id)"
                            class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                            title="Désactiver"
                          >
                            <PauseIcon class="h-5 w-5" />
                          </button>
                          <button 
                            v-else
                            @click="handleReactivateSite(parentItem._id, childItem._id)"
                            class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" 
                            title="Réactiver"
                          >
                            <PlayIcon class="h-5 w-5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  </template>
                </template>
              </tbody>
            </table>
            <div v-if="isLoading" class="absolute inset-0 bg-white bg-opacity-75 flex items-center justify-center">
              <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Pagination controls -->
    <div v-if="totalPages > 1" class="flex items-center justify-between px-4 py-3 bg-white border-t border-gray-200 sm:px-6">
      <div class="flex items-center justify-between w-full">
        <!-- Mobile pagination -->
        <div class="flex justify-between flex-1 sm:hidden">
          <button
            @click="goToPrevPage"
            :disabled="!hasPrevPage"
            class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Précédent
          </button>
          <button
            @click="goToNextPage"
            :disabled="!hasNextPage"
            class="relative ml-3 inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Suivant
          </button>
        </div>
        
        <!-- Desktop pagination -->
        <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
          <div>
            <p class="text-sm text-gray-700">
              Affichage de <span class="font-medium">{{ ((currentPage - 1) * itemsPerPage) + 1 }}</span> à 
              <span class="font-medium">{{ Math.min(currentPage * itemsPerPage, totalItems) }}</span> sur 
              <span class="font-medium">{{ totalItems }}</span> résultats
            </p>
          </div>
          <div class="flex items-center space-x-2">
            <label for="page-size" class="text-sm text-gray-700">Afficher:</label>
            <select
              id="page-size"
              @change="handlePageSizeChangeWithRefresh($event.target.value)"
              :value="itemsPerPage"
              class="rounded-md border-gray-300 py-1 text-sm"
            >
              <option value="10">10</option>
              <option value="25">25</option>
              <option value="50">50</option>
              <option value="100">100</option>
            </select>
            <span class="text-sm text-gray-700">par page</span>
          </div>
          <div>
            <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
              <!-- First page button -->
              <button
                @click="handlePageChange(1)"
                :disabled="currentPage === 1"
                class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
                title="Première page"
              >
                <span class="sr-only">Première page</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M15.79 14.77a.75.75 0 01-1.06.02l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 111.04 1.08L11.832 10l3.938 3.71a.75.75 0 01.02 1.06zm-6 0a.75.75 0 01-1.06.02l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 111.04 1.08L5.832 10l3.938 3.71a.75.75 0 01.02 1.06z" clip-rule="evenodd" />
                </svg>
              </button>

              <!-- Previous page button -->
              <button
                @click="goToPrevPage"
                :disabled="!hasPrevPage"
                class="relative inline-flex items-center px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
                title="Page précédente"
              >
                <span class="sr-only">Précédent</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
                </svg>
              </button>
              
              <template v-for="page in paginationPages" :key="page">
                <button
                  @click="handlePageChange(page)"
                  :class="[
                    page === currentPage
                      ? 'relative z-10 inline-flex items-center bg-primary-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600'
                      : 'relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0'
                  ]"
                >
                  {{ page }}
                </button>
              </template>
              
              <!-- Next page button -->
              <button
                @click="goToNextPage"
                :disabled="!hasNextPage"
                class="relative inline-flex items-center px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
                title="Page suivante"
              >
                <span class="sr-only">Suivant</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                </svg>
              </button>

              <!-- Last page button -->
              <button
                @click="handlePageChange(totalPages)"
                :disabled="currentPage === totalPages"
                class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
                title="Dernière page"
              >
                <span class="sr-only">Dernière page</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M4.21 5.23a.75.75 0 011.06-.02l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 11-1.04-1.08L8.168 10 4.23 6.29a.75.75 0 01-.02-1.06zm6 0a.75.75 0 011.06-.02l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 11-1.04-1.08L14.168 10 10.23 6.29a.75.75 0 01-.02-1.06z" clip-rule="evenodd" />
                </svg>
              </button>
            </nav>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Site creation slide panel -->
    <SlidePanel 
      :open="isSiteCreatePanelOpen" 
      @close="isSiteCreatePanelOpen = false" 
      :title="selectedFournisseurForSite ? `Ajouter un site - ${selectedFournisseurForSite.nom}` : 'Ajouter un site'" 
      size="md"
    >
      <SiteCreateForm 
        v-if="selectedFournisseurForSite" 
        :fournisseur-id="selectedFournisseurForSite._id" 
        @created="handleSiteCreatedWithRefresh" 
        @close="isSiteCreatePanelOpen = false" 
      />
    </SlidePanel>
    
    <!-- Fournisseur edit slide panel -->
    <SlidePanel 
      :open="isEditPanelOpen" 
      @close="isEditPanelOpen = false" 
      title="Modifier le fournisseur" 
      size="md"
    >
      <FournisseurEditForm 
        v-if="selectedFournisseurForEdit" 
        :fournisseur="selectedFournisseurForEdit" 
        @updated="handleFournisseurUpdatedWithRefresh" 
        @close="isEditPanelOpen = false" 
      />
    </SlidePanel>
    
    <!-- Site edit slide panel -->
    <SlidePanel 
      :open="isSiteEditPanelOpen" 
      @close="isSiteEditPanelOpen = false" 
      title="Modifier le site" 
      size="md"
    >
      <SiteEditForm 
        v-if="selectedSiteForEdit && selectedFournisseurIdForSiteEdit" 
        :fournisseur-id="selectedFournisseurIdForSiteEdit"
        :site="selectedSiteForEdit" 
        @updated="handleSiteUpdatedWithRefresh" 
        @close="isSiteEditPanelOpen = false" 
      />
    </SlidePanel>
  </div>
</template>
