// frontend/src/components/StationList.vue
<script setup>
import { ref, computed, onMounted, watch } from 'vue';
import { useLoading } from '../composables/useLoading';
import { useErrorHandler } from '../composables/useErrorHandler';
import api from '../api/axios';
import { PencilSquareIcon, PauseIcon, PlayIcon, MagnifyingGlassIcon, FunnelIcon, ChevronDownIcon } from '@heroicons/vue/24/outline';
import StationEditForm from './stations/StationEditForm.vue';
import SlidePanel from './ui/SlidePanel.vue';
import Button from './ui/Button.vue';
import Select from './ui/Select.vue';

// State
const stations = ref([]);
const statusFilter = ref(''); // '' = Tout, 'active' = Actif, 'inactive' = Inactif
const isEditPanelOpen = ref(false);
const selectedStation = ref(null);
const searchQuery = ref('');
const showFilters = ref(false);

// Pagination state
const currentPage = ref(1);
const totalPages = ref(0);
const totalItems = ref(0);
const itemsPerPage = ref(10);
const hasNextPage = ref(false);
const hasPrevPage = ref(false);
const pagination = ref(null);
const filters = ref({});

// Since filtering is now handled server-side, we just return the stations
const filteredStations = computed(() => {
  return stations.value;
});

// Loading and error handling
const { isLoading, execute } = useLoading();
const { withErrorHandling } = useErrorHandler();

// Fetch data
const fetchStations = async () => {
  await execute(async () => {
    const params = {
      page: currentPage.value,
      limit: itemsPerPage.value,
      search: searchQuery.value,
      status: statusFilter.value,
      sortBy: 'nom',
      sortOrder: 'asc'
    };
    
    const response = await withErrorHandling(
      () => api.get('/stations', { params }),
      'Failed to load stations'
    );
    
    stations.value = response.data.data;
    pagination.value = response.data.pagination;
    filters.value = response.data.filters;
    
    // Update pagination state
    currentPage.value = pagination.value.currentPage;
    totalPages.value = pagination.value.totalPages;
    totalItems.value = pagination.value.totalItems;
    itemsPerPage.value = pagination.value.itemsPerPage;
    hasNextPage.value = pagination.value.hasNextPage;
    hasPrevPage.value = pagination.value.hasPrevPage;
  });
};

onMounted(fetchStations);

// Expose fetchStations function for parent component
defineExpose({ fetchStations });

const formatAddress = (adresse) => {
    if (!adresse) return '';
    return `${adresse.rue}, ${adresse.codePostal} ${adresse.ville}, ${adresse.pays}`;
};

const openEditPanel = (station) => {
    selectedStation.value = station;
    isEditPanelOpen.value = true;
};

const handleStationUpdated = () => {
    isEditPanelOpen.value = false;
    selectedStation.value = null;
    fetchStations();
};

const closeEditPanel = () => {
    isEditPanelOpen.value = false;
    selectedStation.value = null;
};

const deactivateStation = async (stationId) => {
    await execute(async () => {
        await withErrorHandling(
            () => api.delete(`/stations/${stationId}`),
            'Failed to deactivate station'
        );
        await fetchStations(); // Refresh the list
    });
};

const reactivateStation = async (stationId) => {
    await execute(async () => {
        await withErrorHandling(
            () => api.patch(`/stations/${stationId}/reactivate`),
            'Failed to reactivate station'
        );
        await fetchStations(); // Refresh the list
    });
};

// Clear all filters
const clearFilters = () => {
  searchQuery.value = '';
  statusFilter.value = '';
  showFilters.value = false;
  currentPage.value = 1;
  fetchStations();
};

// Watch for filter changes to refetch data
const debouncedFetchStations = (() => {
  let timeout;
  return () => {
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      currentPage.value = 1; // Reset to first page on filter change
      fetchStations();
    }, 300);
  };
})();

// Pagination methods
const goToPage = (page) => {
  if (page >= 1 && page <= totalPages.value) {
    currentPage.value = page;
    fetchStations();
  }
};

const goToPrevPage = () => {
  if (hasPrevPage.value) {
    goToPage(currentPage.value - 1);
  }
};

const goToNextPage = () => {
  if (hasNextPage.value) {
    goToPage(currentPage.value + 1);
  }
};

const changePageSize = (newSize) => {
  itemsPerPage.value = newSize;
  currentPage.value = 1;
  fetchStations();
};

// Count active filters
const activeFiltersCount = computed(() => {
  let count = 0;
  if (searchQuery.value) count++;
  if (statusFilter.value) count++;
  return count;
});

// Status filter options
const statusOptions = [
  { value: '', label: 'Tout' },
  { value: 'active', label: 'Actif' },
  { value: 'inactive', label: 'Inactif' }
];

// Watch for changes
watch(searchQuery, debouncedFetchStations);
watch(statusFilter, debouncedFetchStations);
</script>

<template>
  <div class="space-y-6">
    <!-- Search and Filters -->
    <div class="space-y-4">
      <!-- Search Bar and Filter Toggle -->
      <div class="flex items-center space-x-4">
        <button
          @click="showFilters = !showFilters"
          class="flex-shrink-0 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
        >
          <FunnelIcon class="h-4 w-4 mr-2" />
          Filtres
          <span v-if="activeFiltersCount > 0" class="ml-1 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-primary-600 bg-primary-100 rounded-full">
            {{ activeFiltersCount }}
          </span>
          <ChevronDownIcon 
            class="ml-2 h-4 w-4 transition-transform duration-200" 
            :class="{ 'rotate-180': showFilters }"
          />
        </button>
        
        <div class="flex-1 relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <MagnifyingGlassIcon class="h-5 w-5 text-gray-400" />
          </div>
          <input
            v-model="searchQuery"
            type="text"
            class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
            placeholder="Rechercher par nom, référence, adresse ou contact..."
          />
        </div>
      </div>

      <!-- Filters -->
      <div v-if="showFilters" class="p-4 bg-gray-50 rounded-lg">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Statut</label>
            <Select
              v-model="statusFilter"
              :options="statusOptions"
              placeholder="Sélectionner un statut"
            />
          </div>
          
          <!-- Three empty columns for future filters -->
          <div></div>
          <div></div>
          <div></div>
        </div>
        
        <div class="flex justify-end">
          <Button variant="secondary" size="sm" @click="clearFilters">
            Réinitialiser les filtres
          </Button>
        </div>
      </div>
    </div>

    <div class="flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="relative">
          <table class="min-w-full table-fixed divide-y divide-gray-300">
            <thead>
              <tr>
                <th scope="col" class="min-w-[12rem] py-3.5 pr-3 text-left text-sm font-semibold text-gray-900">Nom</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Identifiant Interne</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Adresse</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Contact</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Statut</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                  <span class="sr-only">Actions</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <tr v-for="station in filteredStations" :key="station._id">
                <td class="whitespace-nowrap py-4 pr-3 text-sm font-medium text-gray-900">{{ station.nom }}</td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ station.identifiantInterne }}</td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ formatAddress(station.adresse) }}</td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <div v-if="station.contactPrincipal">
                    <div>{{ station.contactPrincipal.nom }}</div>
                    <div class="text-gray-400">
                      <a v-if="station.contactPrincipal.email" :href="`mailto:${station.contactPrincipal.email}`" class="text-blue-600 hover:text-blue-800 underline">{{ station.contactPrincipal.email }}</a>
                      <span v-if="station.contactPrincipal.email && station.contactPrincipal.telephone"> / </span>
                      <span v-if="station.contactPrincipal.telephone">{{ station.contactPrincipal.telephone }}</span>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm">
                  <span v-if="station.isActive" class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                    Actif
                  </span>
                  <span v-else class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/20">
                    Inactif
                  </span>
                </td>
                <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                    <div class="flex items-center justify-end gap-x-2">
                        <button @click="openEditPanel(station)" class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" title="Modifier">
                          <PencilSquareIcon class="h-5 w-5" />
                        </button>
                        <button v-if="station.isActive" @click="deactivateStation(station._id)" class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" title="Désactiver">
                          <PauseIcon class="h-5 w-5" />
                        </button>
                        <button v-else @click="reactivateStation(station._id)" class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded transition-colors" title="Réactiver">
                          <PlayIcon class="h-5 w-5" />
                        </button>
                    </div>
                </td>
              </tr>
            </tbody>
          </table>
          <div v-if="isLoading" class="absolute inset-0 bg-white bg-opacity-75 flex items-center justify-center">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Pagination Controls -->
    <div v-if="totalPages > 1" class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6">
      <div class="flex flex-1 justify-between sm:hidden">
        <button
          @click="goToPrevPage"
          :disabled="!hasPrevPage"
          class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Précédent
        </button>
        <button
          @click="goToNextPage"
          :disabled="!hasNextPage"
          class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Suivant
        </button>
      </div>
      <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
        <div>
          <p class="text-sm text-gray-700">
            Affichage de <span class="font-medium">{{ ((currentPage - 1) * itemsPerPage) + 1 }}</span> à 
            <span class="font-medium">{{ Math.min(currentPage * itemsPerPage, totalItems) }}</span> sur 
            <span class="font-medium">{{ totalItems }}</span> résultats
          </p>
        </div>
        <div class="flex items-center space-x-2">
          <label for="page-size" class="text-sm text-gray-700">Afficher:</label>
          <select
            id="page-size"
            @change="changePageSize($event.target.value)"
            :value="itemsPerPage"
            class="rounded-md border-gray-300 py-1 text-sm"
          >
            <option value="10">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
            <option value="100">100</option>
          </select>
          <span class="text-sm text-gray-700">par page</span>
        </div>
        <div>
          <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
            <button
              @click="goToPrevPage"
              :disabled="!hasPrevPage"
              class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="sr-only">Précédent</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
              </svg>
            </button>
            
            <template v-for="page in Array.from({length: Math.min(5, totalPages)}, (_, i) => {
              const start = Math.max(1, currentPage - 2);
              const end = Math.min(totalPages, start + 4);
              return start + i;
            }).filter(p => p <= totalPages)" :key="page">
              <button
                @click="goToPage(page)"
                :class="[
                  page === currentPage
                    ? 'relative z-10 inline-flex items-center bg-primary-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600'
                    : 'relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0'
                ]"
              >
                {{ page }}
              </button>
            </template>
            
            <button
              @click="goToNextPage"
              :disabled="!hasNextPage"
              class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="sr-only">Suivant</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
              </svg>
            </button>
          </nav>
        </div>
      </div>
    </div>
  </div>

  <!-- Edit Panel -->
  <SlidePanel 
    :open="isEditPanelOpen" 
    @close="closeEditPanel" 
    title="Modifier la station"
    size="md"
  >
    <StationEditForm 
      v-if="selectedStation"
      :station="selectedStation"
      @updated="handleStationUpdated"
      @close="closeEditPanel"
    />
  </SlidePanel>
  </div>
</template>

// gestion-emballages-v2/frontend/src/app/features/stations/station-list/station-list.component.ts
import { Component, OnInit, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';

import { Station, StationFilters } from '../../../core/models/station.model';
import { StationService } from '../../../core/services/station.service';
import { AuthService } from '../../../core/services/auth.service';
import { LoadingService } from '../../../core/services/loading.service';
import { ToastService } from '../../../core/services/toast.service';
import { UserRole } from '../../../core/models/user.model';

@Component({
  selector: 'app-station-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-gray-900">Gestion des Stations</h1>
        <button 
          *ngIf="canCreateStation()"
          class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
          [routerLink]="['/stations/nouvelle']">
          Nouvelle Station
        </button>
      </div>

      <!-- Search and Filters -->
      <div class="space-y-4">
        <div class="flex items-center space-x-4">
          <button 
            (click)="showFilters.set(!showFilters())"
            class="flex items-center space-x-2 px-3 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
            <span>Filtres</span>
            <span *ngIf="activeFiltersCount() > 0" 
                  class="bg-blue-600 text-white text-xs px-2 py-1 rounded-full">
              {{ activeFiltersCount() }}
            </span>
          </button>
          
          <div class="flex-1 relative">
            <input
              type="text"
              [(ngModel)]="searchQuery"
              (input)="onSearchChange()"
              placeholder="Rechercher par nom, ville, code postal..."
              class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
            </div>
          </div>
        </div>

        <!-- Filter Panel -->
        <div *ngIf="showFilters()" class="p-4 bg-gray-50 rounded-lg">
          <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Statut</label>
              <select 
                [(ngModel)]="filters.status"
                (change)="applyFilters()"
                class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">
                <option value="">Tout</option>
                <option value="active">Actif</option>
                <option value="inactive">Inactif</option>
              </select>
            </div>
          </div>
          
          <div class="flex justify-end">
            <button 
              (click)="clearFilters()"
              class="px-4 py-2 text-sm text-gray-600 hover:text-gray-800">
              Réinitialiser les filtres
            </button>
          </div>
        </div>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading()" class="text-center py-8">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
        <p class="mt-2 text-gray-600">Chargement...</p>
      </div>

      <!-- Pagination Controls -->
      <div *ngIf="!loading() && totalPages() > 1" class="flex items-center justify-between border-b border-gray-200 px-6 py-2">
        <div class="text-xs text-gray-700">
          Affichage de {{ (currentPage() - 1) * itemsPerPage() + 1 }} à {{ Math.min(currentPage() * itemsPerPage(), totalItems()) }} sur {{ totalItems() }} résultats
        </div>
        <div class="flex items-center space-x-4">
          <div class="flex items-center space-x-2">
            <span class="text-xs text-gray-700">Afficher:</span>
            <select [value]="itemsPerPage()" (change)="changeItemsPerPage($event)" 
                    class="border border-gray-300 rounded px-2 py-0.5 text-xs bg-white w-14 focus:ring-1 focus:ring-primary-500 focus:border-primary-500">
              <option value="10">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
            </select>
            <span class="text-xs text-gray-700">par page</span>
          </div>
          <div class="flex space-x-1">
            <button [disabled]="currentPage() === 1" (click)="goToPage(currentPage() - 1)"
                    class="px-2 py-0.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed">
              Précédent
            </button>
            <button *ngFor="let page of getVisiblePages()" (click)="goToPage(page)"
                    [class.bg-primary-100]="page === currentPage()"
                    [class.text-primary-700]="page === currentPage()"
                    class="px-2 py-0.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50">
              {{ page }}
            </button>
            <button [disabled]="currentPage() === totalPages()" (click)="goToPage(currentPage() + 1)"
                    class="px-2 py-0.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed">
              Suivant
            </button>
          </div>
        </div>
      </div>

      <!-- Desktop Table -->
      <div *ngIf="!loading()" class="hidden md:block bg-white shadow rounded-lg overflow-hidden">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer"
                  (click)="toggleSort('nom')">
                Nom
                <svg *ngIf="filters.sortBy === 'nom'" class="inline w-4 h-4 ml-1" fill="currentColor" viewBox="0 0 20 20">
                  <path *ngIf="filters.sortOrder === 'ASC'" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"/>
                  <path *ngIf="filters.sortOrder === 'DESC'" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"/>
                </svg>
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Adresse</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Contact</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Statut</th>
              <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr *ngFor="let station of stations()" class="hover:bg-gray-50">
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm font-medium text-gray-900">{{ station.nom }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ station.adresse }}</div>
                <div class="text-sm text-gray-500">{{ station.codePostal }} {{ station.ville }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ station.contact }}</div>
                <div class="text-sm text-gray-500">{{ station.email }}</div>
                <div class="text-sm text-gray-500">{{ station.telephone }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span [class]="getStatusBadgeClass(station.isActive)">
                  {{ station.isActive ? 'Actif' : 'Inactif' }}
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <div class="flex items-center justify-end space-x-2">
                  <button 
                    [routerLink]="['/stations', station.id]"
                    class="text-blue-600 hover:text-blue-900">
                    Voir
                  </button>
                  <button 
                    *ngIf="canEditStation()"
                    [routerLink]="['/stations', station.id, 'modifier']"
                    class="text-green-600 hover:text-green-900">
                    Modifier
                  </button>
                  <button 
                    *ngIf="canToggleStatus()"
                    (click)="toggleStatus(station)"
                    [class]="station.isActive ? 'text-red-600 hover:text-red-900' : 'text-green-600 hover:text-green-900'">
                    {{ station.isActive ? 'Désactiver' : 'Activer' }}
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Mobile Cards -->
      <div *ngIf="!loading()" class="md:hidden space-y-4">
        <div *ngFor="let station of stations()" 
             class="bg-white p-4 rounded-lg shadow border border-gray-200">
          <div class="flex items-start justify-between mb-3">
            <div>
              <h3 class="font-medium text-gray-900">{{ station.nom }}</h3>
              <p class="text-sm text-gray-500">{{ station.ville }}</p>
            </div>
            <span [class]="getStatusBadgeClass(station.isActive)">
              {{ station.isActive ? 'Actif' : 'Inactif' }}
            </span>
          </div>
          
          <div class="space-y-2 text-sm">
            <div><span class="font-medium">Adresse:</span> {{ station.adresse }}</div>
            <div><span class="font-medium">Code postal:</span> {{ station.codePostal }}</div>
            <div *ngIf="station.contact"><span class="font-medium">Contact:</span> {{ station.contact }}</div>
            <div *ngIf="station.email"><span class="font-medium">Email:</span> {{ station.email }}</div>
            <div *ngIf="station.telephone"><span class="font-medium">Téléphone:</span> {{ station.telephone }}</div>
          </div>
          
          <div class="flex items-center justify-end space-x-3 mt-4 pt-3 border-t border-gray-200">
            <button 
              [routerLink]="['/stations', station.id]"
              class="text-blue-600 hover:text-blue-900 text-sm">
              Voir
            </button>
            <button 
              *ngIf="canEditStation()"
              [routerLink]="['/stations', station.id, 'modifier']"
              class="text-green-600 hover:text-green-900 text-sm">
              Modifier
            </button>
            <button 
              *ngIf="canToggleStatus()"
              (click)="toggleStatus(station)"
              [class]="station.isActive ? 'text-red-600 hover:text-red-900 text-sm' : 'text-green-600 hover:text-green-900 text-sm'">
              {{ station.isActive ? 'Désactiver' : 'Activer' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Empty State -->
      <div *ngIf="!loading() && stations().length === 0" class="text-center py-12">
        <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-4m-4 0H3m2 0h3M9 7h6m-6 4h6m-6 4h6"/>
        </svg>
        <p class="mt-4 text-gray-500">Aucune station trouvée</p>
        <button 
          *ngIf="canCreateStation()"
          [routerLink]="['/stations/nouvelle']"
          class="mt-4 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
          Créer la première station
        </button>
      </div>
    </div>
  `
})
export class StationListComponent implements OnInit {
  // Signals
  stations = signal<Station[]>([]);
  loading = signal(false);
  showFilters = signal(false);
  currentPage = signal(1);
  totalPages = signal(0);
  totalItems = signal(0);
  itemsPerPage = signal(10);

  // Filter state
  searchQuery = '';
  filters: StationFilters = {
    page: 1,
    limit: 10,
    search: '',
    sortBy: 'nom',
    sortOrder: 'ASC',
    status: ''
  };

  // Computed
  activeFiltersCount = computed(() => {
    let count = 0;
    if (this.filters.status) count++;
    return count;
  });

  private searchTimeout: any;

  // Expose Math to template
  Math = Math;

  constructor(
    private stationService: StationService,
    private authService: AuthService,
    private loadingService: LoadingService,
    private toastService: ToastService
  ) {}

  ngOnInit() {
    this.loadStations();
  }

  async loadStations() {
    this.loading.set(true);
    try {
      const response = await this.stationService.getStations(this.filters);
      this.stations.set(response.data);
      this.totalPages.set(response.totalPages);
      this.totalItems.set(response.total);
      this.currentPage.set(response.page);
    } catch (error) {
      this.toastService.error('Erreur lors du chargement des stations');
    } finally {
      this.loading.set(false);
    }
  }

  onSearchChange() {
    if (this.searchTimeout) {
      clearTimeout(this.searchTimeout);
    }
    this.searchTimeout = setTimeout(() => {
      this.filters.search = this.searchQuery;
      this.filters.page = 1;
      this.loadStations();
    }, 300);
  }

  applyFilters() {
    this.filters.page = 1;
    this.loadStations();
  }

  clearFilters() {
    this.searchQuery = '';
    this.filters = {
      page: 1,
      limit: 10,
      search: '',
      sortBy: 'nom',
      sortOrder: 'ASC',
      status: ''
    };
    this.loadStations();
  }

  toggleSort(field: string) {
    if (this.filters.sortBy === field) {
      this.filters.sortOrder = this.filters.sortOrder === 'ASC' ? 'DESC' : 'ASC';
    } else {
      this.filters.sortBy = field;
      this.filters.sortOrder = 'ASC';
    }
    this.loadStations();
  }

  goToPage(page: number) {
    if (page >= 1 && page <= this.totalPages()) {
      this.filters.page = page;
      this.loadStations();
    }
  }

  changeItemsPerPage(event: Event) {
    const target = event.target as HTMLSelectElement;
    this.itemsPerPage.set(parseInt(target.value));
    this.filters.limit = parseInt(target.value);
    this.filters.page = 1;
    this.loadStations();
  }

  getVisiblePages(): number[] {
    const total = this.totalPages();
    const current = this.currentPage();
    const pages: number[] = [];

    if (total <= 7) {
      for (let i = 1; i <= total; i++) {
        pages.push(i);
      }
    } else {
      if (current <= 4) {
        for (let i = 1; i <= 5; i++) {
          pages.push(i);
        }
        pages.push(-1, total);
      } else if (current >= total - 3) {
        pages.push(1, -1);
        for (let i = total - 4; i <= total; i++) {
          pages.push(i);
        }
      } else {
        pages.push(1, -1);
        for (let i = current - 1; i <= current + 1; i++) {
          pages.push(i);
        }
        pages.push(-1, total);
      }
    }

    return pages;
  }

  async toggleStatus(station: Station) {
    try {
      if (station.isActive) {
        await this.stationService.deactivateStation(station.id);
        this.toastService.success('Station désactivée avec succès');
      } else {
        await this.stationService.reactivateStation(station.id);
        this.toastService.success('Station réactivée avec succès');
      }
      this.loadStations();
    } catch (error) {
      this.toastService.error('Erreur lors de la modification du statut');
    }
  }

  getStatusBadgeClass(isActive: boolean): string {
    return isActive 
      ? 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800'
      : 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800';
  }

  // Permission methods
  canCreateStation(): boolean {
    const user = this.authService.currentUser();
    return user?.role === UserRole.MANAGER || user?.role === UserRole.HANDLER;
  }

  canEditStation(): boolean {
    const user = this.authService.currentUser();
    return user?.role === UserRole.MANAGER || user?.role === UserRole.HANDLER;
  }

  canToggleStatus(): boolean {
    const user = this.authService.currentUser();
    return user?.role === UserRole.MANAGER || user?.role === UserRole.HANDLER;
  }
}
