// gestion-emballages-v2/frontend/src/app/features/users/user-list/user-list.component.ts
import { Component, inject, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup } from '@angular/forms';
import { RouterModule } from '@angular/router';

import { UserService, UserFilters, PaginatedUsersResponse } from '@core/services/user.service';
import { AuthService } from '@core/services/auth.service';
import { NotificationService } from '@core/services/notification.service';
import { LoadingSpinnerComponent } from '@shared/components/loading-spinner/loading-spinner.component';
import { User, UserRole, EntityType } from '@core/models/user.model';

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterModule,
    LoadingSpinnerComponent
  ],
  template: `
    <div class="space-y-6">
      
      <!-- Header -->
      <div class="flex justify-between items-center">
        <div>
          <h1 class="text-2xl font-bold text-gray-900">Utilisateurs</h1>
          <p class="text-gray-600">Gestion des comptes utilisateurs</p>
        </div>
        
        <button
          *ngIf="authService.canAccessUserManagement()"
          type="button"
          class="btn-primary"
          (click)="openCreateModal()">
          <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
          Nouvel utilisateur
        </button>
      </div>

      <!-- Search and Filters -->
      <div class="bg-white rounded-lg shadow-sm p-6">
        <form [formGroup]="searchForm" class="space-y-4">
          
          <!-- Search Bar -->
          <div class="flex items-center space-x-4">
            <button
              type="button"
              class="inline-flex items-center px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50"
              (click)="showFilters.set(!showFilters())">
              <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.207A1 1 0 013 6.5V4z" />
              </svg>
              Filtres
              <span *ngIf="activeFiltersCount() > 0" 
                    class="ml-1 inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-primary-100 text-primary-800">
                {{ activeFiltersCount() }}
              </span>
            </button>
            
            <div class="flex-1 relative">
              <svg class="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <input
                type="text"
                formControlName="search"
                class="form-input pl-10"
                placeholder="Rechercher par nom ou email..."
                (input)="onSearchChange()">
            </div>
          </div>

          <!-- Filters Panel -->
          <div *ngIf="showFilters()" class="border-t pt-4 space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
              
              <!-- Status Filter -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Statut</label>
                <select formControlName="status" class="form-select" (change)="onFiltersChange()">
                  <option value="">Tous</option>
                  <option value="active">Actifs</option>
                  <option value="inactive">Inactifs</option>
                </select>
              </div>

              <!-- Role Filter -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Rôle</label>
                <select formControlName="role" class="form-select" (change)="onFiltersChange()">
                  <option value="">Tous les rôles</option>
                  <option *ngFor="let role of availableRoles()" [value]="role">
                    {{ userService.getRoleDisplayName(role) }}
                  </option>
                </select>
              </div>

              <!-- Entity Type Filter -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Type d'entité</label>
                <select formControlName="entiteType" class="form-select" (change)="onFiltersChange()">
                  <option value="">Tous</option>
                  <option value="Station">Station</option>
                  <option value="Fournisseur">Fournisseur</option>
                </select>
              </div>

              <!-- Sort By -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Trier par</label>
                <select formControlName="sortBy" class="form-select" (change)="onFiltersChange()">
                  <option value="nomComplet">Nom</option>
                  <option value="email">Email</option>
                  <option value="role">Rôle</option>
                  <option value="createdAt">Date de création</option>
                </select>
              </div>
            </div>

            <div class="flex justify-end">
              <button
                type="button"
                class="btn-outline"
                (click)="clearFilters()">
                Réinitialiser les filtres
              </button>
            </div>
          </div>
        </form>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading()" class="flex justify-center py-12">
        <app-loading-spinner size="lg" message="Chargement des utilisateurs..."></app-loading-spinner>
      </div>

      <!-- Users Table -->
      <div *ngIf="!loading()" class="bg-white rounded-lg shadow-sm overflow-hidden">
        
        <!-- Desktop Table -->
        <div class="hidden md:block">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Utilisateur
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Rôle
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Entité
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Statut
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Créé le
                </th>
                <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr *ngFor="let user of users()" class="hover:bg-gray-50">
                
                <!-- User Info -->
                <td class="px-6 py-4">
                  <div class="flex items-center">
                    <div class="h-10 w-10 bg-primary-600 rounded-full flex items-center justify-center">
                      <span class="text-sm font-medium text-white">
                        {{ userService.getUserInitials(user.nomComplet) }}
                      </span>
                    </div>
                    <div class="ml-4">
                      <div class="font-medium text-gray-900">{{ user.nomComplet }}</div>
                      <div class="text-sm text-gray-500">{{ user.email }}</div>
                    </div>
                  </div>
                </td>

                <!-- Role -->
                <td class="px-6 py-4">
                  <span [class]="getRoleClass(user.role)">
                    {{ userService.getRoleDisplayName(user.role) }}
                  </span>
                </td>

                <!-- Entity -->
                <td class="px-6 py-4">
                  <div class="text-sm text-gray-900">
                    <div *ngIf="user.station">
                      <span class="font-medium">{{ user.station.nom }}</span>
                      <div class="text-xs text-gray-500">Station</div>
                    </div>
                    <div *ngIf="user.fournisseur">
                      <span class="font-medium">{{ user.fournisseur.nom }}</span>
                      <div class="text-xs text-gray-500">Fournisseur</div>
                    </div>
                    <div *ngIf="!user.station && !user.fournisseur" class="text-gray-400">
                      Aucune
                    </div>
                  </div>
                </td>

                <!-- Status -->
                <td class="px-6 py-4">
                  <span [class]="getStatusClass(user.isActive)">
                    {{ user.isActive ? 'Actif' : 'Inactif' }}
                  </span>
                </td>

                <!-- Created Date -->
                <td class="px-6 py-4">
                  <div class="text-sm text-gray-900">
                    {{ formatDate(user.createdAt) }}
                  </div>
                </td>

                <!-- Actions -->
                <td class="px-6 py-4 text-right text-sm font-medium">
                  <div class="flex items-center justify-end space-x-2">
                    <button
                      type="button"
                      class="text-primary-600 hover:text-primary-900"
                      (click)="viewUser(user)"
                      title="Voir les détails">
                      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                      </svg>
                    </button>

                    <button
                      *ngIf="canEditUser(user)"
                      type="button"
                      class="text-gray-600 hover:text-gray-900"
                      (click)="editUser(user)"
                      title="Modifier">
                      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                    </button>

                    <button
                      *ngIf="canDeleteUser(user)"
                      type="button"
                      [class]="user.isActive ? 'text-red-600 hover:text-red-900' : 'text-green-600 hover:text-green-900'"
                      (click)="toggleUserStatus(user)"
                      [title]="user.isActive ? 'Désactiver' : 'Réactiver'">
                      <svg *ngIf="user.isActive" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <svg *ngIf="!user.isActive" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Mobile Cards -->
        <div class="md:hidden space-y-4 p-4">
          <div *ngFor="let user of users()" 
               class="border border-gray-200 rounded-lg p-4 space-y-3">
            
            <div class="flex items-center space-x-3">
              <div class="h-10 w-10 bg-primary-600 rounded-full flex items-center justify-center">
                <span class="text-sm font-medium text-white">
                  {{ userService.getUserInitials(user.nomComplet) }}
                </span>
              </div>
              <div class="flex-1">
                <h3 class="font-medium text-gray-900">{{ user.nomComplet }}</h3>
                <p class="text-sm text-gray-500">{{ user.email }}</p>
              </div>
              <span [class]="getStatusClass(user.isActive)">
                {{ user.isActive ? 'Actif' : 'Inactif' }}
              </span>
            </div>

            <div class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span class="text-gray-500">Rôle:</span>
                <span class="ml-1 text-gray-900">{{ userService.getRoleDisplayName(user.role) }}</span>
              </div>
              <div>
                <span class="text-gray-500">Entité:</span>
                <span class="ml-1 text-gray-900">
                  {{ user.station?.nom || user.fournisseur?.nom || 'Aucune' }}
                </span>
              </div>
            </div>

            <div class="text-sm">
              <span class="text-gray-500">Créé le:</span>
              <span class="ml-1 text-gray-900">{{ formatDate(user.createdAt) }}</span>
            </div>

            <!-- Mobile Actions -->
            <div class="flex justify-end space-x-2 pt-2 border-t border-gray-100">
              <button
                type="button"
                class="text-sm text-primary-600 hover:text-primary-900"
                (click)="viewUser(user)">
                Voir
              </button>
              <button
                *ngIf="canEditUser(user)"
                type="button"
                class="text-sm text-gray-600 hover:text-gray-900"
                (click)="editUser(user)">
                Modifier
              </button>
              <button
                *ngIf="canDeleteUser(user)"
                type="button"
                [class]="user.isActive ? 'text-sm text-red-600 hover:text-red-900' : 'text-sm text-green-600 hover:text-green-900'"
                (click)="toggleUserStatus(user)">
                {{ user.isActive ? 'Désactiver' : 'Réactiver' }}
              </button>
            </div>
          </div>
        </div>

        <!-- Empty State -->
        <div *ngIf="users().length === 0" class="text-center py-12">
          <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13.5-9a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z" />
          </svg>
          <h3 class="mt-2 text-sm font-medium text-gray-900">Aucun utilisateur trouvé</h3>
          <p class="mt-1 text-sm text-gray-500">
            {{ searchForm.get('search')?.value ? 'Essayez de modifier vos critères de recherche.' : 'Commencez par créer un nouvel utilisateur.' }}
          </p>
        </div>
      </div>

      <!-- Pagination -->
      <div *ngIf="paginatedResponse() && paginatedResponse()!.totalPages > 1" 
           class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6 rounded-lg">
        
        <!-- Results Info -->
        <div class="flex flex-1 justify-between sm:hidden">
          <button
            [disabled]="!paginatedResponse()?.hasPreviousPage"
            (click)="goToPage(currentPage() - 1)"
            class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed">
            Précédent
          </button>
          <button
            [disabled]="!paginatedResponse()?.hasNextPage"
            (click)="goToPage(currentPage() + 1)"
            class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed">
            Suivant
          </button>
        </div>
        
        <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
          <div>
            <p class="text-sm text-gray-700">
              Affichage de
              <span class="font-medium">{{ getResultStart() }}</span>
              à
              <span class="font-medium">{{ getResultEnd() }}</span>
              sur
              <span class="font-medium">{{ paginatedResponse()?.total }}</span>
              résultats
            </p>
          </div>
          
          <div class="flex items-center space-x-2">
            <label class="text-sm text-gray-700">Afficher:</label>
            <select
              [value]="itemsPerPage()"
              (change)="changeItemsPerPage($event)"
              class="form-select text-sm">
              <option value="10">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
            </select>
            <span class="text-sm text-gray-700">par page</span>
          </div>
          
          <div>
            <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
              <button
                [disabled]="!paginatedResponse()?.hasPreviousPage"
                (click)="goToPage(currentPage() - 1)"
                class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
                </svg>
              </button>
              
              <button
                *ngFor="let page of getVisiblePages()"
                [class]="getPageButtonClass(page)"
                (click)="goToPage(page)">
                {{ page }}
              </button>
              
              <button
                [disabled]="!paginatedResponse()?.hasNextPage"
                (click)="goToPage(currentPage() + 1)"
                class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                </svg>
              </button>
            </nav>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class UserListComponent implements OnInit {
  private fb = inject(FormBuilder);
  public userService = inject(UserService);
  public authService = inject(AuthService);
  private notificationService = inject(NotificationService);

  // Reactive state
  public loading = signal(false);
  public showFilters = signal(false);
  public users = signal<User[]>([]);
  public paginatedResponse = signal<PaginatedUsersResponse | null>(null);
  public currentPage = signal(1);
  public itemsPerPage = signal(20);

  // Computed values
  public activeFiltersCount = computed(() => {
    const formValue = this.searchForm.value;
    let count = 0;
    if (formValue.status) count++;
    if (formValue.role) count++;
    if (formValue.entiteType) count++;
    if (formValue.sortBy !== 'nomComplet') count++;
    return count;
  });

  public availableRoles = computed(() => {
    const currentUserRole = this.authService.userRole();
    return currentUserRole ? this.userService.getAvailableRoles(currentUserRole) : [];
  });

  // Form
  public searchForm: FormGroup = this.fb.group({
    search: [''],
    status: [''],
    role: [''],
    entiteType: [''],
    sortBy: ['nomComplet'],
    sortOrder: ['ASC']
  });

  private searchTimeout: any;

  ngOnInit() {
    this.loadUsers();
  }

  loadUsers() {
    this.loading.set(true);
    
    const filters: UserFilters = {
      page: this.currentPage(),
      limit: this.itemsPerPage(),
      ...this.searchForm.value
    };

    this.userService.getUsers(filters).subscribe({
      next: (response) => {
        this.users.set(response.data);
        this.paginatedResponse.set(response);
        this.loading.set(false);
      },
      error: (error) => {
        console.error('Error loading users:', error);
        this.loading.set(false);
      }
    });
  }

  onSearchChange() {
    if (this.searchTimeout) {
      clearTimeout(this.searchTimeout);
    }
    
    this.searchTimeout = setTimeout(() => {
      this.currentPage.set(1);
      this.loadUsers();
    }, 300);
  }

  onFiltersChange() {
    this.currentPage.set(1);
    this.loadUsers();
  }

  clearFilters() {
    this.searchForm.patchValue({
      search: '',
      status: '',
      role: '',
      entiteType: '',
      sortBy: 'nomComplet',
      sortOrder: 'ASC'
    });
    this.currentPage.set(1);
    this.loadUsers();
  }

  // Pagination methods
  goToPage(page: number) {
    this.currentPage.set(page);
    this.loadUsers();
  }

  changeItemsPerPage(event: Event) {
    const target = event.target as HTMLSelectElement;
    this.itemsPerPage.set(parseInt(target.value));
    this.currentPage.set(1);
    this.loadUsers();
  }

  getVisiblePages(): number[] {
    const totalPages = this.paginatedResponse()?.totalPages || 0;
    const current = this.currentPage();
    const delta = 2;
    const range = [];
    
    for (let i = Math.max(2, current - delta); i <= Math.min(totalPages - 1, current + delta); i++) {
      range.push(i);
    }
    
    if (current - delta > 2) {
      range.unshift(-1);
    }
    if (current + delta < totalPages - 1) {
      range.push(-1);
    }
    
    if (totalPages > 1) {
      range.unshift(1);
      if (totalPages > 1) {
        range.push(totalPages);
      }
    }
    
    return range.filter((v, i, arr) => arr.indexOf(v) === i && v > 0);
  }

  getPageButtonClass(page: number): string {
    const baseClasses = 'relative inline-flex items-center px-4 py-2 text-sm font-semibold';
    if (page === this.currentPage()) {
      return `${baseClasses} z-10 bg-primary-600 text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600`;
    }
    return `${baseClasses} text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0`;
  }

  getResultStart(): number {
    const response = this.paginatedResponse();
    if (!response) return 0;
    return (response.page - 1) * response.limit + 1;
  }

  getResultEnd(): number {
    const response = this.paginatedResponse();
    if (!response) return 0;
    return Math.min(response.page * response.limit, response.total);
  }

  // User actions
  viewUser(user: User) {
    console.log('View user:', user);
  }

  editUser(user: User) {
    console.log('Edit user:', user);
  }

  openCreateModal() {
    console.log('Create new user');
  }

  toggleUserStatus(user: User) {
    const action = user.isActive ? 'désactiver' : 'réactiver';
    
    if (confirm(`Êtes-vous sûr de vouloir ${action} cet utilisateur ?`)) {
      if (user.isActive) {
        this.userService.deleteUser(user.id).subscribe({
          next: () => {
            this.notificationService.showSuccess('Utilisateur désactivé avec succès');
            this.loadUsers();
          },
          error: (error: any) => {
            console.error('Error deactivating user:', error);
            this.notificationService.showError('Erreur lors de la désactivation');
          }
        });
      } else {
        this.userService.reactivateUser(user.id).subscribe({
          next: () => {
            this.notificationService.showSuccess('Utilisateur réactivé avec succès');
            this.loadUsers();
          },
          error: (error: any) => {
            console.error('Error reactivating user:', error);
            this.notificationService.showError('Erreur lors de la réactivation');
          }
        });
      }
    }
  }

  // Permission methods
  canEditUser(user: User): boolean {
    const currentUserRole = this.authService.userRole();
    return currentUserRole ? this.userService.canEditUser(currentUserRole, user.role) : false;
  }

  canDeleteUser(user: User): boolean {
    const currentUserRole = this.authService.userRole();
    return currentUserRole ? this.userService.canDeleteUser(currentUserRole, user.role) : false;
  }

  // Utility methods
  getRoleClass(role: UserRole): string {
    const roleClasses = {
      [UserRole.MANAGER]: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800',
      [UserRole.GESTIONNAIRE]: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800',
      [UserRole.STATION]: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800',
      [UserRole.FOURNISSEUR]: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-orange-100 text-orange-800'
    };
    return roleClasses[role] || 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800';
  }

  getStatusClass(isActive: boolean): string {
    return isActive 
      ? 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800'
      : 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800';
  }

  formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('fr-FR', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  }
}

// frontend/src/components/users/UserList.vue
<script setup>
import { ref, onMounted, computed, watch } from 'vue';
import { useLoading } from '../../composables/useLoading';
import { useErrorHandler } from '../../composables/useErrorHandler';
import api from '../../api/axios';
import { PencilSquareIcon, PlayIcon, PauseIcon, MagnifyingGlassIcon, FunnelIcon, ChevronDownIcon, ExclamationTriangleIcon } from '@heroicons/vue/24/outline';
import SlidePanel from '../ui/SlidePanel.vue';
import UserEditForm from './UserEditForm.vue';
import Select from '../ui/Select.vue';
import Button from '../ui/Button.vue';

// State
const users = ref([]);
const statusFilter = ref(''); // '' = Tout, 'active' = Actif, 'inactive' = Inactif
const isEditPanelOpen = ref(false);
const selectedUser = ref(null);
const searchQuery = ref('');
const roleFilter = ref('');
const showFilters = ref(false);

// Pagination state
const currentPage = ref(1);
const totalPages = ref(0);
const totalItems = ref(0);
const itemsPerPage = ref(10);
const hasNextPage = ref(false);
const hasPrevPage = ref(false);
const pagination = ref(null);
const filters = ref({});

// Loading and error handling
const { isLoading, execute } = useLoading();
const { withErrorHandling } = useErrorHandler();

// Fetch data
const fetchUsers = async () => {
  await execute(async () => {
    const params = {
      page: currentPage.value,
      limit: itemsPerPage.value,
      search: searchQuery.value,
      role: roleFilter.value,
      status: statusFilter.value,
      sortBy: 'nomComplet',
      sortOrder: 'asc'
    };
    
    const response = await withErrorHandling(
      () => api.get('/users', { params }),
      'Failed to load users'
    );
    
    users.value = response.data.data;
    pagination.value = response.data.pagination;
    filters.value = response.data.filters;
    
    // Update pagination state
    currentPage.value = pagination.value.currentPage;
    totalPages.value = pagination.value.totalPages;
    totalItems.value = pagination.value.totalItems;
    itemsPerPage.value = pagination.value.itemsPerPage;
    hasNextPage.value = pagination.value.hasNextPage;
    hasPrevPage.value = pagination.value.hasPrevPage;
  });
};

const openEditPanel = (user) => {
    selectedUser.value = user;
    isEditPanelOpen.value = true;
};

const handleUserUpdated = () => {
    isEditPanelOpen.value = false;
    fetchUsers();
};

const softDeleteUser = async (userId) => {
    await execute(async () => {
        await withErrorHandling(
            () => api.delete(`/users/${userId}`),
            'Failed to delete user'
        );
        await fetchUsers(); // Refresh the list
    });
};

const reactivateUser = async (userId) => {
    await execute(async () => {
        await withErrorHandling(
            () => api.patch(`/users/${userId}/reactivate`),
            'Failed to reactivate user'
        );
        await fetchUsers(); // Refresh the list
    });
};

onMounted(fetchUsers);

// Role filter options
const roleOptions = computed(() => {
  const roles = ['Manager', 'Gestionnaire', 'Station', 'Fournisseur'];
  return [
    { value: '', label: 'Tous les rôles' },
    ...roles.map(role => ({ value: role, label: role }))
  ];
});

// Status filter options
const statusOptions = [
  { value: '', label: 'Tout' },
  { value: 'active', label: 'Actif' },
  { value: 'inactive', label: 'Inactif' }
];

// Since filtering is now handled server-side, we just return the users
const filteredUsers = computed(() => {
  return users.value;
});

// Clear all filters
const clearFilters = () => {
  searchQuery.value = '';
  roleFilter.value = '';
  statusFilter.value = '';
  showFilters.value = false;
  currentPage.value = 1;
  fetchUsers();
};

// Watch for filter changes to refetch data
const debouncedFetchUsers = (() => {
  let timeout;
  return () => {
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      currentPage.value = 1; // Reset to first page on filter change
      fetchUsers();
    }, 300);
  };
})();

// Pagination methods
const goToPage = (page) => {
  if (page >= 1 && page <= totalPages.value) {
    currentPage.value = page;
    fetchUsers();
  }
};

const goToPrevPage = () => {
  if (hasPrevPage.value) {
    goToPage(currentPage.value - 1);
  }
};

const goToNextPage = () => {
  if (hasNextPage.value) {
    goToPage(currentPage.value + 1);
  }
};

const changePageSize = (newSize) => {
  itemsPerPage.value = newSize;
  currentPage.value = 1;
  fetchUsers();
};

// Watch for changes
watch(searchQuery, debouncedFetchUsers);
watch(roleFilter, debouncedFetchUsers);
watch(statusFilter, debouncedFetchUsers);

// Count active filters
const activeFiltersCount = computed(() => {
  let count = 0;
  if (searchQuery.value) count++;
  if (roleFilter.value) count++;
  if (statusFilter.value) count++;
  return count;
});

// Helper function to check if linked entity is deactivated
const isEntityDeactivated = (user) => {
  if (!user.entiteId) return false;
  
  // Check if the linked entity (station or supplier) is deactivated
  return user.entiteId.isActive === false;
};

// Helper function to get entity warning text
const getEntityWarningText = (user) => {
  if (!isEntityDeactivated(user)) return '';
  
  if (user.role === 'Station') {
    return 'station désactivée';
  } else if (user.role === 'Fournisseur') {
    return 'fournisseur désactivé';
  }
  return 'entité désactivée';
};

// Expose fetchUsers function for parent component
defineExpose({ fetchUsers });
</script>

<template>
  <div class="space-y-6">
    <!-- Search and Filters -->
    <div class="space-y-4">
      <!-- Search Bar and Filter Toggle -->
      <div class="flex items-center space-x-4">
        <button
          @click="showFilters = !showFilters"
          class="flex-shrink-0 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
        >
          <FunnelIcon class="h-4 w-4 mr-2" />
          Filtres
          <span v-if="activeFiltersCount > 0" class="ml-1 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-primary-600 bg-primary-100 rounded-full">
            {{ activeFiltersCount }}
          </span>
          <ChevronDownIcon 
            class="ml-2 h-4 w-4 transition-transform duration-200" 
            :class="{ 'rotate-180': showFilters }"
          />
        </button>
        
        <div class="flex-1 relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <MagnifyingGlassIcon class="h-5 w-5 text-gray-400" />
          </div>
          <input
            v-model="searchQuery"
            type="text"
            class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
            placeholder="Rechercher par nom, email ou entité..."
          />
        </div>
      </div>

      <!-- Filters -->
      <div v-if="showFilters" class="p-4 bg-gray-50 rounded-lg">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Statut</label>
            <Select
              v-model="statusFilter"
              :options="statusOptions"
              placeholder="Sélectionner un statut"
            />
          </div>
          
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Rôle</label>
            <Select
              v-model="roleFilter"
              :options="roleOptions"
              placeholder="Sélectionner un rôle"
            />
          </div>
          
          <!-- Two empty columns for future filters -->
          <div></div>
          <div></div>
        </div>
        
        <div class="flex justify-end">
          <Button variant="secondary" size="sm" @click="clearFilters">
            Réinitialiser les filtres
          </Button>
        </div>
      </div>
    </div>
    <!-- Mobile card view -->
    <div class="block md:hidden">
      <div class="space-y-3">
        <div
          v-for="user in filteredUsers"
          :key="user._id"
          class="bg-white p-4 rounded-lg border border-gray-200"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1 min-w-0">
              <div class="flex items-center justify-between mb-2">
                <h3 class="text-sm font-semibold text-gray-900 truncate">{{ user.nomComplet }}</h3>
                <span 
                  class="inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ml-2"
                  :class="user.isActive ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'"
                >
                  {{ user.isActive ? 'Actif' : 'Inactif' }}
                </span>
              </div>
              <p class="text-sm text-gray-500 truncate">{{ user.email }}</p>
              <p class="text-xs text-gray-400 mt-1">
                {{ user.role }}
                <span v-if="user.entiteId && user.entiteId.nom">
                  ({{ user.entiteId.nom }}<span v-if="isEntityDeactivated(user)" class="inline-flex items-center text-amber-600 cursor-help" :title="getEntityWarningText(user)"> <ExclamationTriangleIcon class="h-3 w-3 ml-1" /></span>)
                </span>
              </p>
            </div>
          </div>
          <div class="mt-3 flex justify-end gap-x-2">
            <button 
              @click="openEditPanel(user)" 
              class="p-2 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
              title="Modifier"
            >
              <PencilSquareIcon class="h-5 w-5" />
            </button>
            <button 
              v-if="user.isActive"
              @click="softDeleteUser(user._id)" 
              class="p-2 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
              title="Désactiver"
            >
              <PauseIcon class="h-5 w-5" />
            </button>
            <button 
              v-else
              @click="reactivateUser(user._id)" 
              class="p-2 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
              title="Réactiver"
            >
              <PlayIcon class="h-5 w-5" />
            </button>
          </div>
        </div>
      </div>
      <!-- Loading state for mobile -->
      <div v-if="isLoading" class="flex items-center justify-center py-8">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
      </div>
    </div>

    <!-- Desktop table view -->
    <div class="hidden md:block flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
            <div class="relative">
            <table class="min-w-full table-fixed divide-y divide-gray-300">
                <thead>
                <tr>
                    <th scope="col" class="min-w-[12rem] py-3.5 pr-3 text-left text-sm font-semibold text-gray-900">Nom Complet</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Rôle</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Statut</th>
                    <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                    <span class="sr-only">Actions</span>
                    </th>
                </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">
                <tr v-for="user in filteredUsers" :key="user._id">
                    <td class="whitespace-nowrap py-4 pr-3 text-sm font-medium text-gray-900">{{ user.nomComplet }}</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ user.email }}</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        {{ user.role }}
                        <span v-if="user.entiteId && user.entiteId.nom" class="text-gray-400">
                            ({{ user.entiteId.nom }}<span v-if="isEntityDeactivated(user)" class="inline-flex items-center text-amber-600 cursor-help" :title="getEntityWarningText(user)"> <ExclamationTriangleIcon class="h-4 w-4 ml-1" /></span>)
                        </span>
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <span class="inline-flex items-center rounded-md px-2 py-1 text-xs font-medium" :class="user.isActive ? 'bg-green-50 text-green-700 ring-1 ring-inset ring-green-600/20' : 'bg-red-50 text-red-700 ring-1 ring-inset ring-red-600/20'">
                            {{ user.isActive ? 'Actif' : 'Inactif' }}
                        </span>
                    </td>
                    <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                        <div class="flex items-center justify-end gap-x-2">
                            <button 
                                @click="openEditPanel(user)" 
                                class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
                                title="Modifier"
                            >
                                <PencilSquareIcon class="h-5 w-5" />
                            </button>
                            <button 
                                v-if="user.isActive"
                                @click="softDeleteUser(user._id)" 
                                class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
                                title="Désactiver"
                            >
                                <PauseIcon class="h-5 w-5" />
                            </button>
                            <button 
                                v-else
                                @click="reactivateUser(user._id)" 
                                class="p-1.5 text-primary-600 hover:text-primary-900 hover:bg-primary-50 rounded-lg transition-colors"
                                title="Réactiver"
                            >
                                <PlayIcon class="h-5 w-5" />
                            </button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
            <div v-if="isLoading" class="absolute inset-0 bg-white bg-opacity-75 flex items-center justify-center">
                <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
            </div>
            </div>
        </div>
        </div>
    </div>

    <!-- Pagination Controls -->
    <div v-if="totalPages > 1" class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6">
      <div class="flex flex-1 justify-between sm:hidden">
        <button
          @click="goToPrevPage"
          :disabled="!hasPrevPage"
          class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Précédent
        </button>
        <button
          @click="goToNextPage"
          :disabled="!hasNextPage"
          class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Suivant
        </button>
      </div>
      <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
        <div>
          <p class="text-sm text-gray-700">
            Affichage de <span class="font-medium">{{ ((currentPage - 1) * itemsPerPage) + 1 }}</span> à 
            <span class="font-medium">{{ Math.min(currentPage * itemsPerPage, totalItems) }}</span> sur 
            <span class="font-medium">{{ totalItems }}</span> résultats
          </p>
        </div>
        <div class="flex items-center space-x-2">
          <label for="page-size" class="text-sm text-gray-700">Afficher:</label>
          <select
            id="page-size"
            @change="changePageSize($event.target.value)"
            :value="itemsPerPage"
            class="rounded-md border-gray-300 py-1 text-sm"
          >
            <option value="10">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
            <option value="100">100</option>
          </select>
          <span class="text-sm text-gray-700">par page</span>
        </div>
        <div>
          <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
            <button
              @click="goToPrevPage"
              :disabled="!hasPrevPage"
              class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="sr-only">Précédent</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
              </svg>
            </button>
            
            <template v-for="page in Array.from({length: Math.min(5, totalPages)}, (_, i) => {
              const start = Math.max(1, currentPage - 2);
              const end = Math.min(totalPages, start + 4);
              return start + i;
            }).filter(p => p <= totalPages)" :key="page">
              <button
                @click="goToPage(page)"
                :class="[
                  page === currentPage
                    ? 'relative z-10 inline-flex items-center bg-primary-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600'
                    : 'relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0'
                ]"
              >
                {{ page }}
              </button>
            </template>
            
            <button
              @click="goToNextPage"
              :disabled="!hasNextPage"
              class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="sr-only">Suivant</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
              </svg>
            </button>
          </nav>
        </div>
      </div>
    </div>

    <SlidePanel :open="isEditPanelOpen" @close="isEditPanelOpen = false" title="Modifier l'utilisateur" size="md">
        <UserEditForm v-if="selectedUser" :user="selectedUser" @updated="handleUserUpdated" @close="isEditPanelOpen = false" />
    </SlidePanel>
  </div>
</template>
